use_frameworks!
platform :ios, '8.0'

target 'RIoc_Example' do
  pod 'RIoc', :path => '../'

  target 'RIoc_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
